Repository openshift-pipelines/pipeline-service, pull requests merged in 2022-08, with the labels that each got.

#177 Fix referenced github url
  gitops/sre/environment/kcp/kustomization.yaml
Labels: lgtm

#175 Fix minor issues in local install scripts
  DEVELOPMENT.md
  local/kcp/start.sh
  local/kind/setup.sh
  local/utils.sh
Labels: lgtm

#176 Update piplines-service or Pipelines-Service or Pipelines Service to 'Pipeline Service'
  DEVELOPMENT.md
  README.md
  ckcp/openshift_dev_setup.sh
  docs/kcp-registration.md
  docs/operations.md
  docs/sre/examples/providers/environment/flavors/compute/base/kustomization.yaml
  docs/sre/examples/providers/environment/kcp/kustomization.yaml
  docs/sre/examples/single_cluster/environment/compute/mycluster-com/kustomization.yaml
  docs/sre/examples/single_cluster/environment/kcp/kustomization.yaml
  exploration/argocd-external/images/argocd-registrar/Dockerfile
  exploration/argocd-external/images/argocd-registrar/register.sh
  gitops/README.md
  gitops/argocd/argo-apps/cert-manager-operator.yaml
  gitops/argocd/argo-apps/tektoncd.yaml
  gitops/argocd/argocd.yaml
  gitops/pac/README.md
  gitops/pac/setup.sh
  gitops/sre/.tekton/gateway-deployment.yaml
  gitops/sre/.tekton/kcp-registration.yaml
  gitops/sre/environment/kcp/kustomization.yaml
  images/access-setup/README.md
  images/access-setup/content/bin/common.sh
  images/access-setup/content/bin/setup_compute.sh
  images/access-setup/content/bin/setup_kcp.sh
  images/cluster-setup/Dockerfile
  images/cluster-setup/install.sh
  images/gateway-deployment/Dockerfile
  images/gateway-deployment/install.sh
  images/kcp-registrar/Dockerfile
  images/kcp-registrar/register.sh
  local/argocd/setup.sh
  local/kcp/pipelines-service-org.yaml
  local/kcp/start.sh
  local/kind/setup.sh
  local/utils.sh
  test/images/shellcheck/Dockerfile
Labels: lgtm

#198 add owners file for openshift-ci to manage merge process
  OWNERS
Labels: needs-ok-to-test, do-not-merge/invalid-owners-file

#192 Upgrade kcp to release-0.7
  .github/workflows/access-setup-image.yaml
  .github/workflows/kcp-registrar-image.yaml
  DEPENDENCIES.md
  ckcp/openshift/overlays/dev/kustomization.yaml
  docs/kcp-registration.md
  images/access-setup/Dockerfile
  images/kcp-registrar/Dockerfile
  images/kcp-registrar/register.sh
  local/kcp/start.sh
Labels: lgtm

#205 Explicitly set the type by workspace creation
  images/access-setup/content/bin/setup_kcp.sh
  images/gateway-deployment/install.sh
  images/kcp-registrar/register.sh
Labels: lgtm, approved

#206 Add new recordings to the readme page
  README.md
Labels: lgtm, approved

#207 added Hadolint configuration file
  test/config/hadolint.yaml
Labels: lgtm, approved

#203 Improving Developer Experience with ckcp
  ckcp/README.md
  ckcp/config.yaml
  ckcp/hack/util/update-git-reference.sh
  ckcp/openshift_dev_setup.sh
  gitops/pac/setup.sh
  images/access-setup/content/bin/setup_compute.sh
Labels: enhancement, lgtm, approved

#208 fix cert-manager sync with ckcp
  ckcp/openshift_dev_setup.sh
Labels: enhancement, lgtm, approved

#211 bugfix: ckcp/test.sh
  ckcp/test.sh
Labels: approved

#210 added config file for SAST tools Checkov
  test/config/checkov.yaml
Labels: lgtm, approved

#204 PLNSRVCE-522 : Containers - Clair - Vulnerability Scanner
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/periodic-scanner-quay.yaml
  test/images/vulnerability-scan/Dockerfile
  test/images/vulnerability-scan/scan-image.sh
  test/images/vulnerability-scan/scan.sh
Labels: lgtm, approved

#209 fix issues that hadolint reported
  images/access-setup/Dockerfile
  images/cluster-setup/Dockerfile
  images/kcp-registrar/Dockerfile
  test/images/shellcheck/Dockerfile
Labels: lgtm, approved

#214 fixed minor issues reported by hadolint
  test/images/vulnerability-scan/Dockerfile
Labels: lgtm

#217 Make the location of kcp runtime files configurable
  local/kcp/start.sh
Labels: lgtm, approved

#215 Add probes to ckcp
  ckcp/openshift/base/deployment.yaml
Labels: lgtm, approved
