Repository openshift-pipelines/pipeline-service, pull requests merged in 2022-11, with the labels that each got.

#344 Fix ckcp
  developer/ckcp/openshift_dev_setup.sh
Labels: lgtm, approved

#334 Use more recent version of Tekton Chains
  DEPENDENCIES.md
  operator/gitops/argocd/tekton-chains/base/chains-controller-deployment.yaml
Labels: needs-ok-to-test

#345 PLNSRVCE-778 : Replacing set-output with GITHUB_OUTPUT as it is deprecated in Github actions
  .github/workflows/argocd-registrar-image.yaml
  .github/workflows/build-push-images.yaml
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/kcp-upgrade.yaml
  .github/workflows/periodic-scanner-quay.yaml
Labels: lgtm, approved

#308 Use CONTAINER_ENGINE instead of podman
  ci/images/quay-upload/image-upload.sh
  developer/ckcp/README.md
  developer/docs/DEVELOPMENT.md
  developer/images/devenv/run.sh
  developer/local/kind/setup.sh
  operator/images/access-setup/content/bin/setup_compute.sh
Labels: approved

#309 Allow workspace to be configured when deploying ckcp
  developer/ckcp/README.md
  developer/ckcp/config.yaml
  developer/ckcp/openshift_dev_setup.sh
  developer/local/kcp/start.sh
  operator/images/access-setup/content/bin/setup_kcp.sh
  operator/images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#342 Enable automerge in update-pipeline-service
  operator/images/update-pipeline-service/bin/gitlab.sh
  operator/images/update-pipeline-service/bin/gitlab_open_mr.sh
  operator/images/update-pipeline-service/bin/update.sh
Labels: approved

#350 fix update-pipeline-service
  operator/images/update-pipeline-service/bin/gitlab.sh
Labels: approved

#349 PLNSRVCE-818: Generalize the Github Action "Periodic image scanner" so that other teams can reuse it
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/periodic-scanner-quay.yaml
  ci/images/vulnerability-scan/common/utils.sh
  ci/images/vulnerability-scan/scan.sh
Labels: lgtm, approved

#335 Modify tekton-chains generated yaml files into a kustomization based structure
  operator/images/access-setup/content/bin/setup_compute.sh
  operator/images/cluster-setup/bin/install.sh
Labels: lgtm, approved

#347 Capture return status in the function call inline to fix the issue with vulnerability scanners
  ci/images/vulnerability-scan/common/utils.sh
  ci/images/vulnerability-scan/scan-image.sh
  ci/images/vulnerability-scan/scan.sh
Labels: lgtm, approved

#336 consumer: Add scripts to access service
  .tekton/pipeline-service-static-code-analysis.yaml
  consumer/README.md
  consumer/bind_to.sh
  consumer/hack/bind.sh
  consumer/hack/run_test_workload.sh
  consumer/run_test_workload.sh
Labels: approved

#354 Create configmap for configuring tekton-results
  operator/gitops/argocd/tekton-results/configmap.yaml
  operator/gitops/argocd/tekton-results/deployment.yaml
Labels: lgtm, approved

#355 Shellcheck
  .shellcheckrc
  .tekton/pipeline-service-static-code-analysis.yaml
  ci/config/shellcheck.rc
  operator/images/update-pipeline-service/bin/update.sh
Labels: approved

#360 Use upstream version of Tekton Chains - 0.13.0
  DEPENDENCIES.md
  operator/gitops/argocd/tekton-chains/base/chains-controller-deployment.yaml
  operator/gitops/argocd/tekton-chains/base/kustomization.yaml
Labels: lgtm, needs-ok-to-test, approved

#361 fix access-setup/setup_kcp.sh
  operator/images/access-setup/content/bin/setup_kcp.sh
Labels: lgtm, approved

#359 change SA name from pac-manager
  developer/ckcp/openshift_dev_setup.sh
  operator/docs/sre/examples/providers/credentials/kubeconfig/kcp/my-workspace.kubeconfig
  operator/docs/sre/examples/single_cluster/credentials/kubeconfig/kcp/my-workspace.kubeconfig
  operator/gitops/compute/pipeline-service-manager/kustomization.yaml
  operator/gitops/compute/pipeline-service-manager/namespace.yaml
  operator/gitops/compute/pipeline-service-manager/pipeline-service-manager.yaml
  operator/gitops/compute/pipeline-service-manager/role.yaml
  operator/gitops/compute/pipeline-service-manager/rolebinding.yaml
  operator/gitops/kcp/pipeline-service-manager/kustomization.yaml
  operator/gitops/kcp/pipeline-service-manager/namespace.yaml
  operator/gitops/kcp/pipeline-service-manager/pipeline-service-manager.yaml
  operator/gitops/kcp/pipeline-service-manager/role.yaml
  operator/gitops/kcp/pipeline-service-manager/rolebinding.yaml
  operator/images/access-setup/README.md
  operator/images/access-setup/content/bin/setup_compute.sh
  operator/images/access-setup/content/bin/setup_kcp.sh
Labels: lgtm, approved

#364 Update OWNERS
  OWNERS
Labels: approved

#353 implemented ckcp CI with pipeline-service
  .tekton/pipeline-service-ckcp-testing.yaml
Labels: lgtm, approved

#358 ckcp can now be run without any app
  developer/ckcp/openshift_dev_setup.sh
  operator/images/kcp-registrar/bin/register.sh
Labels: approved

#365 Fix bitwarden installation
  developer/images/devenv/Dockerfile
  operator/images/cluster-setup/Dockerfile
  operator/images/cluster-setup/content/bin/install.sh
  shared/hack/install.sh
Labels: lgtm, approved
