Repository openshift-pipelines/pipeline-service, pull requests merged in 2022-09, with the labels that each got.

#219 Document how params need to be passed
  local/kcp/start.sh
Labels: lgtm, approved

#220 Check for local binaries
  ckcp/openshift_dev_setup.sh
Labels: lgtm, needs-ok-to-test, approved

#223 add debug switch for debugging ckcp error
  ckcp/openshift_dev_setup.sh
Labels: approved

#222 Improve README in ckcp
  DEVELOPMENT.md
  ckcp/README.md
  ckcp/openshift_dev_setup.sh
  ckcp/test.sh
  gitops/README.md
  gitops/argocd/tektoncd/tekton-config.yaml
  images/access-setup/content/bin/setup_compute.sh
Labels: lgtm, approved

#225 Improve ckcp deployment to avoid cert-manger error
  ckcp/openshift_dev_setup.sh
  images/cluster-setup/Dockerfile
  images/cluster-setup/bin/install.sh
  images/cluster-setup/bin/utils.sh
Labels: lgtm, approved

#224 Combine 6 different actions into one for building and pushing images
  .github/workflows/access-setup-image.yaml
  .github/workflows/build-push-images.yaml
  .github/workflows/cluster-setup-image.yaml
  .github/workflows/gateway-deployment-image.yaml
  .github/workflows/kcp-registrar-image.yaml
  .github/workflows/shellcheck-image.yaml
Labels: approved

#226 Created a util script for vulnerability scan image
  test/images/vulnerability-scan/common/utils.sh
  test/images/vulnerability-scan/scan-image.sh
  test/images/vulnerability-scan/scan.sh
Labels: approved

#230 Update ckcp/README.md
  ckcp/README.md
Labels: lgtm, approved

#229 fix tektonconfig sync
  gitops/argocd/tektoncd/kustomization.yaml
  gitops/argocd/tektoncd/tekton-config.yaml
Labels: lgtm

#231 PLNSRVCE-697: Upgrade kcp to v0.8.0
  .github/workflows/build-push-images.yaml
  .github/workflows/local-dev-ci.yaml
  DEPENDENCIES.md
  ckcp/openshift/overlays/dev/kustomization.yaml
  ckcp/openshift_dev_setup.sh
  docs/kcp-registration.md
  images/kcp-registrar/Dockerfile
  images/kcp-registrar/register.sh
  local/kcp/start.sh
Labels: approved

#235 Fix handling of PARAMS in local/kcp/start.sh
  local/kcp/start.sh
Labels: lgtm, approved

#236 Improve UX of local/kcp/start.sh
  local/kcp/start.sh
Labels: lgtm, approved

#239 Check if the installed kcp plugin is latest
  ckcp/openshift_dev_setup.sh
Labels: lgtm, approved

#240 Fix broken links in ckcp docs
  ckcp/README.md
Labels: lgtm, approved, ok-to-test

#233 fixed issue of testing pipelinerun
  ckcp/test.sh
Labels: lgtm, approved

#243 Added permissions for upgrade.sh for kcp-upgrade github action
  images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#244 Upgrade kcp to the latest version
  .github/workflows/build-push-images.yaml
  .github/workflows/local-dev-ci.yaml
  DEPENDENCIES.md
  ckcp/openshift/overlays/dev/kustomization.yaml
  config/config.yaml
  docs/kcp-registration.md
  images/kcp-registrar/register.sh
Labels: lgtm, approved

#126 Implement tekton-chains
  DEPENDENCIES.md
  ckcp/manifests/test/tekton-chains/kustomization.yaml
  ckcp/manifests/test/tekton-chains/simple-copy-pipeline.yaml
  ckcp/test.sh
  gitops/README.md
  gitops/argocd/argo-apps/kustomization.yaml
  gitops/argocd/argo-apps/tekton-chains.yaml
  gitops/argocd/tekton-chains/base/allow-argocd-to-manage.yaml
  gitops/argocd/tekton-chains/base/chains-config.yaml
  gitops/argocd/tekton-chains/base/chains-controller-deployment.yaml
  gitops/argocd/tekton-chains/base/chains-secrets-config.yaml
  gitops/argocd/tekton-chains/base/kustomization.yaml
  gitops/argocd/tekton-chains/base/signing-secrets.yaml
  gitops/argocd/tekton-chains/overlays/openshift/chains-secrets-config-patch.yaml
  gitops/argocd/tekton-chains/overlays/openshift/kustomization.yaml
  gitops/argocd/tekton-chains/overlays/openshift/security-context-fix.yaml
  gitops/sre/credentials/manifests/README.md
  images/access-setup/content/bin/setup_compute.sh
  images/cluster-setup/bin/install.sh
Labels: lgtm, approved

#114 Always register clusters to KCP
  images/kcp-registrar/register.sh
Labels: lgtm, approved

#250 fix issue with yq in setup_compute script
  images/access-setup/content/bin/setup_compute.sh
Labels: bug, lgtm, approved

#245 Record server CA during registration
  images/kcp-registrar/register.sh
Labels: lgtm, approved, ok-to-test

#251 Fix missing yq dependency in kcp-registrar Dockerfile
  images/kcp-registrar/Dockerfile
Labels: approved

#253 Propagate debug flag in ckcp/openshift_dev_setup.sh
  ckcp/openshift_dev_setup.sh
Labels: approved

#252 Fix missing openssl dependency in kcp-registrar Dockerfile
  DEPENDENCIES.md
  images/kcp-registrar/Dockerfile
Labels: lgtm, approved

#242 Provide a development container to minimize devenv setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/build-push-images.yaml
  CONTRIBUTING.md
  config/dependencies.yaml
  local/utils.sh
  test/images/devenv/Dockerfile
  test/images/devenv/README.md
  test/images/devenv/install.sh
  test/images/devenv/run.sh
Labels: lgtm, approved

#257 Fix missing jq dependency in cluster-setup Dockerfile
  images/cluster-setup/Dockerfile
Labels: approved

#255 Updating kcp upgrade script
  images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#256 Provide CRs to sync as parameter in register script
  ckcp/openshift_dev_setup.sh
  config/config.yaml
  images/kcp-registrar/register.sh
Labels: lgtm

#259 Fix devenv image generation
  .github/workflows/build-push-images.yaml
Labels: lgtm, approved

#262 Corrected the image path in periodic and individual image scanners
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/periodic-scanner-quay.yaml
Labels: lgtm, approved

#264 fix: macos compatibility: base64 flag name
  images/kcp-registrar/register.sh
Labels: lgtm, needs-ok-to-test, approved
