Repository openshift-pipelines/pipeline-service, pull requests merged in 2022-10, with the labels that each got.

#234 Script to reset ckcp
  ckcp/README.md
  ckcp/hack/util/reset_ckcp.sh
Labels: lgtm, approved

#265 Print kubeconfig of kcp and cluster at the end of ckcp script
  ckcp/openshift_dev_setup.sh
Labels: lgtm, approved

#266 Add Mo3m3n to approvers
  OWNERS
Labels: lgtm, approved

#267 Modify upgrade_kcp workflows
  .github/workflows/kcp-upgrade.yaml
  images/kcp-upgrade/upgrade.sh
Labels: approved

#271 Upgrade kcp from 0.8.2 to 0.9.0
  .github/workflows/build-push-images.yaml
  .github/workflows/local-dev-ci.yaml
  DEPENDENCIES.md
  ckcp/openshift/overlays/dev/kustomization.yaml
  config/config.yaml
  config/dependencies.yaml
  docs/kcp-registration.md
  images/kcp-registrar/Dockerfile
  images/kcp-registrar/register.sh
Labels: lgtm, approved

#273 Adding a new path for kcp upgrade and a new line in ckcp script
  ckcp/openshift_dev_setup.sh
  images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#263 PLNSRVCE-671 : Automate the process to upgrade pipeline-service on staging cluster
  .github/workflows/build-push-images.yaml
  images/update-pipeline-service/Dockerfile
  images/update-pipeline-service/bin/gitlab_open_mr.sh
  images/update-pipeline-service/bin/update.sh
  test/images/quay-upload/Dockerfile
  test/images/quay-upload/image-upload.sh
Labels: lgtm, approved

#227 PLNSRVCE-420 : Implement Tekton results for openshift development
  ckcp/manifests/tekton-results-db/openshift/configmap.yaml
  ckcp/manifests/tekton-results-db/openshift/kustomization.yaml
  ckcp/manifests/tekton-results-db/openshift/namespace.yaml
  ckcp/manifests/tekton-results-db/openshift/service.yaml
  ckcp/manifests/tekton-results-db/openshift/statefulset.yaml
  ckcp/openshift_dev_setup.sh
  ckcp/test.sh
  config/config.yaml
  gitops/argocd/argo-apps/kustomization.yaml
  gitops/argocd/argo-apps/tekton-results.yaml
  gitops/argocd/tekton-results/README.md
  gitops/argocd/tekton-results/allow-argocd-to-manage.yaml
  gitops/argocd/tekton-results/cert.yaml
  gitops/argocd/tekton-results/configmap.yaml
  gitops/argocd/tekton-results/deployment.yaml
  gitops/argocd/tekton-results/kustomization.yaml
  gitops/argocd/tekton-results/permissions.yaml
  gitops/argocd/tekton-results/route.yaml
  gitops/argocd/tekton-results/service-account.yaml
  images/access-setup/README.md
  images/access-setup/content/bin/setup_compute.sh
  images/cluster-setup/bin/install.sh
Labels: lgtm, approved, ok-to-test

#270 Fix kcp-upgrade workflow
  .github/workflows/kcp-upgrade.yaml
  images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#274 Fixes failing github action step push to quay.io due to variable name mismatch
  test/images/quay-upload/image-upload.sh
Labels: lgtm, approved

#275 Fix gitlab pipeline - Modify the name of the job used in Gitlab ci to fetch the current commit
  images/update-pipeline-service/bin/gitlab_open_mr.sh
  images/update-pipeline-service/bin/update.sh
Labels: lgtm, approved

#278 Update Dockerfiles to use SHA instead of tags
  exploration/argocd-external/images/argocd-registrar/Dockerfile
  images/access-setup/Dockerfile
  images/cluster-setup/Dockerfile
  images/gateway-deployment/Dockerfile
  images/kcp-registrar/Dockerfile
  images/update-pipeline-service/Dockerfile
  test/images/devenv/Dockerfile
  test/images/quay-upload/Dockerfile
  test/images/shellcheck/Dockerfile
  test/images/vulnerability-scan/Dockerfile
Labels: lgtm, approved

#277 Update tekton results images to pipeline-service built images
  gitops/argocd/tekton-results/deployment.yaml
Labels: lgtm, approved

#279 fix: Invalid var assignement in impage-upload.sh
  test/images/quay-upload/image-upload.sh
Labels: lgtm, approved

#282 Updated the registry value used while sending a GET API request on quay-upload/image-upload.sh
  .github/workflows/build-push-images.yaml
Labels: lgtm, approved

#283 Fix image SHA for the devenv image
  test/images/devenv/Dockerfile
Labels: approved

#280 Refactor image upload
  test/images/quay-upload/image-upload.sh
Labels: lgtm, approved

#285 image-upload: Add usage and fix registry path
  .github/workflows/build-push-images.yaml
  test/images/quay-upload/image-upload.sh
Labels: lgtm, approved

#286 Upgrade SHA for devenv image
  test/images/devenv/Dockerfile
Labels: approved

#288 PLNSRVCE-646 : Sync workflows
  .github/workflows/individual-image-scanner-quay.yaml
Labels: lgtm, approved

#295 Fix build-push-images.yaml
  .github/workflows/build-push-images.yaml
Labels: approved

#294 Remove runs.tekton.dev from kcp-syncer
  ckcp/openshift_dev_setup.sh
  config/config.yaml
  images/kcp-registrar/bin/register.sh
Labels: lgtm, approved

#292 Upgrade shellcheck from v0.7.1 to v0.8.0
  ckcp/test.sh
  config/dependencies.yaml
  test/images/shellcheck/Dockerfile
Labels: approved

#290 Upgrade yq version from v4.14.5 to v4.28.1
  DEPENDENCIES.md
  config/dependencies.yaml
Labels: lgtm, approved

#296 build yamllint image
  .github/workflows/build-push-images.yaml
  test/images/yamllint/Dockerfile
Labels: approved

#297 fix workflow and reset_ckcp.sh
  .github/workflows/individual-image-scanner-quay.yaml
  ckcp/hack/util/reset_ckcp.sh
Labels: lgtm, approved

#293 Upgrade tekton-cli from v0.26.0 to v0.27.0
  DEPENDENCIES.md
  config/dependencies.yaml
Labels: approved

#298 Use full version tag for the podman image
  test/images/devenv/Dockerfile
Labels: approved

#302 Fix the path as a previous PR changed the path of register.sh script
  images/kcp-upgrade/upgrade.sh
Labels: lgtm, approved

#304 Fix kcp-upgrade to handle access-setup
  images/access-setup/Dockerfile
  images/kcp-upgrade/upgrade.sh
Labels: approved

#291 Improve devenv/install.sh script
  test/images/devenv/install.sh
Labels: approved

#307 PLNSRVCE-777 : [M9]Deploy the workspace controller onto the staging cluster
  ckcp/openshift_dev_setup.sh
  gitops/README.md
  gitops/sre/environment/kcp/workspace-controller/base/kustomization.yaml
  gitops/sre/environment/kcp/workspace-controller/overlays/kustomization.yaml
  images/kcp-registrar/bin/register.sh
Labels: lgtm, approved

#300 Create dogfooding CI jobs for static code analysis
  .tekton/pipeline-service-static-code-analysis.yaml
  .tekton/shellcheck-yaml-lint-pipeline.yaml
Labels: lgtm, approved

#318 Fix shellcheck errors
  images/update-pipeline-service/bin/gitlab_open_mr.sh
  test/images/quay-upload/image-upload.sh
Labels: approved

#312 use kcp-registrar to configure gateway in compute WS
  ckcp/openshift_dev_setup.sh
  gitops/sre/environment/kcp/gateway-bindings/kustomization.yaml
  gitops/sre/environment/kcp/registration/kustomization.yaml
  images/gateway-deployment/Dockerfile
  images/gateway-deployment/install.sh
  images/kcp-registrar/Dockerfile
  images/kcp-registrar/bin/register.sh
Labels: lgtm, approved

#320 Remove gateway-deployment from github workflows
  .github/workflows/build-push-images.yaml
  .github/workflows/individual-image-scanner-quay.yaml
  docs/gateway.md
  gitops/sre/.tekton/gateway-deployment.yaml
  test/images/vulnerability-scan/scan.sh
Labels: lgtm, approved

#314 refactor: Create 'consumer' folder
  consumer/README.md
  consumer/bind_to.sh
  consumer/manifests/apibinding/apibinding.yaml
  consumer/manifests/workloads/hello-world.yaml
  consumer/run_test_workload.sh
Labels: approved

#319 Update dependencies to include grpc_cli
  shared/config/dependencies.yaml
  test/images/devenv/Dockerfile
  test/images/devenv/install.sh
Labels: approved

#321 Fix devenv build
  shared/config/dependencies.yaml
  test/images/devenv/install.sh
Labels: approved

#316 refactor: Create 'ci' folder
  .github/workflows/build-push-images.yaml
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/periodic-scanner-quay.yaml
  .tekton/pipeline-service-static-code-analysis.yaml
  ci/README.md
  ci/config/checkov.yaml
  ci/config/hadolint.yaml
  ci/config/yamllint.yaml
  ci/docs/continuous_integation.md
  ci/docs/static_checks.md
  ci/images/quay-upload/Dockerfile
  ci/images/quay-upload/image-upload.sh
  ci/images/shellcheck/Dockerfile
  ci/images/vulnerability-scan/Dockerfile
  ci/images/vulnerability-scan/common/utils.sh
  ci/images/vulnerability-scan/scan-image.sh
  ci/images/vulnerability-scan/scan.sh
  ci/images/yamllint/Dockerfile
Labels: lgtm, approved

#310 Fix reset_ckcp.sh when using a custom workspace
  ckcp/hack/util/reset_ckcp.sh
Labels: approved

#322 Fix the name and path of vulnerability image in github actions
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/periodic-scanner-quay.yaml
Labels: lgtm, approved

#315 refactor: Create 'architect' folder
  README.md
  architect/gateway.md
  architect/images/components.png
  architect/images/gateway.png
  architect/images/phase1.png
  architect/images/phase2.png
  architect/images/triggers.png
  architect/images/vanilla.png
  architect/kcp-registration.md
  architect/operations.md
  architect/phase1.md
  architect/phase2.md
  ckcp/README.md
  gitops/README.md
Labels: approved

#329 Configuring a failure timeout
  .tekton/pipeline-service-static-code-analysis.yaml
Labels: lgtm, approved

#326 refactor: Create 'operator' folder (move docs)
  operator/docs/kcp-registration.md
  operator/docs/operations.md
  operator/docs/sre/examples/providers/README.md
  operator/docs/sre/examples/providers/credentials/kubeconfig/compute/p1.clusterA.kubeconfig
  operator/docs/sre/examples/providers/credentials/kubeconfig/compute/p1.clusterB.kubeconfig
  operator/docs/sre/examples/providers/credentials/kubeconfig/compute/p2.kubeconfig
  operator/docs/sre/examples/providers/credentials/kubeconfig/kcp/my-workspace.kubeconfig
  operator/docs/sre/examples/providers/environment/compute/provider1/east/api-clusterA-provider1-com/kustomization.yaml
  operator/docs/sre/examples/providers/environment/compute/provider1/west/api-clusterB-provider1-com/kustomization.yaml
  operator/docs/sre/examples/providers/environment/compute/provider2/api-foobar-clusterA-provider2-com/kustomization.yaml
  operator/docs/sre/examples/providers/environment/compute/provider2/api-foobaz-clusterB-provider2-com/kustomization.yaml
  operator/docs/sre/examples/providers/environment/flavors/compute/base/kustomization.yaml
  operator/docs/sre/examples/providers/environment/flavors/compute/overlays/unstable/kustomization.yaml
  operator/docs/sre/examples/providers/environment/kcp/kustomization.yaml
  operator/docs/sre/examples/single_cluster/README.md
  operator/docs/sre/examples/single_cluster/credentials/kubeconfig/compute/my-cluster.kubeconfig
  operator/docs/sre/examples/single_cluster/credentials/kubeconfig/kcp/my-workspace.kubeconfig
  operator/docs/sre/examples/single_cluster/environment/compute/mycluster-com/kustomization.yaml
  operator/docs/sre/examples/single_cluster/environment/kcp/kustomization.yaml
Labels: approved

#325 refactor: Create 'operator' folder (move images)
  .github/workflows/build-push-images.yaml
  .github/workflows/individual-image-scanner-quay.yaml
  .github/workflows/kcp-upgrade.yaml
  developer/ckcp/openshift_dev_setup.sh
  gitops/README.md
  gitops/argocd/tekton-chains/base/signing-secrets.yaml
  operator/cert-manager/cert-manager.yaml
  operator/cert-manager/kustomization.yaml
  operator/cert-manager/namespace.yaml
  operator/cert-manager/operatorgroup.yaml
  operator/images/access-setup/Dockerfile
  operator/images/access-setup/README.md
  operator/images/access-setup/content/bin/common.sh
  operator/images/access-setup/content/bin/setup_compute.sh
  operator/images/access-setup/content/bin/setup_kcp.sh
  operator/images/cluster-setup/Dockerfile
  operator/images/cluster-setup/bin/install.sh
  operator/images/cluster-setup/bin/utils.sh
  operator/images/kcp-registrar/Dockerfile
  operator/images/kcp-registrar/bin/register.sh
  operator/images/kcp-registrar/data/syncer-patch.yaml
  operator/images/kcp-upgrade/upgrade.sh
  operator/images/update-pipeline-service/Dockerfile
  operator/images/update-pipeline-service/bin/gitlab_open_mr.sh
  operator/images/update-pipeline-service/bin/update.sh
Labels: approved

#337 Fix links in markdown files
  README.md
  architect/gateway.md
  architect/img/gateway.png
  architect/img/phase1.png
  architect/img/phase2.png
  architect/img/triggers.png
  architect/img/vanilla.png
  architect/phase1.md
  architect/phase2.md
  developer/ckcp/README.md
  developer/docs/DEVELOPMENT.md
  developer/docs/README.md
  operator/docs/img/components.png
  operator/docs/kcp-registration.md
  operator/docs/operations.md
  operator/gitops/README.md
Labels: approved

#338 Fix cert-manager path in argocd app
  developer/ckcp/hack/util/reset_ckcp.sh
  developer/ckcp/openshift_dev_setup.sh
  operator/gitops/argocd/argo-apps/cert-manager-operator.yaml
Labels: lgtm, approved

#341 Fix devenv
  developer/images/devenv/Dockerfile
Labels: approved

#340 Fix YAML formatting for .github/workflows/build-push-images.yaml
  .github/workflows/build-push-images.yaml
Labels: approved
